# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\FilterBlackListedExtension
        public: true
        tags:
            - { name: twig.extension }

    globals.app.twig_extension:
        class: AppBundle\Twig\GlobalsExtension
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        public: true
        tags:
            - { name: twig.extension }

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@service_container", "@doctrine.orm.entity_manager"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
